import test from "node:test";
import assert from "node:assert/strict";
import * as XLSX from "xlsx";
import { parseExcel } from "../src/lib/excel-parser";

function buildWorkbook(rows: unknown[][], sheetName = "High End"): ArrayBuffer {
  const worksheet = XLSX.utils.aoa_to_sheet(rows);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
  return XLSX.write(workbook, { type: "array", bookType: "xlsx" }) as ArrayBuffer;
}

function encodeUtf8(text: string): ArrayBuffer {
  const bytes = new TextEncoder().encode(text);
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
}

test("parseExcel reads header-based rows and keeps Japanese values", () => {
  const buffer = buildWorkbook([
    ["No", "日本語名", "英語名", "セット", "言語", "状態", "JP価格", "EN価格", "カテゴリ", "備考", "画像URL"],
    [1, "意志の力", "Force of Will", "ALL", "JP/EN", "NM", "24,000円", "30,000", "ハイエンド", "", "https://example.com/fow.jpg"],
  ]);

  const result = parseExcel(buffer);

  assert.equal(result.sheets.length, 1);
  assert.equal(result.warnings.length, 0);
  assert.equal(result.sheets[0].cards.length, 1);
  assert.equal(result.sheets[0].cards[0].nameJp, "意志の力");
  assert.equal(result.sheets[0].cards[0].priceJp, 24000);
  assert.equal(result.sheets[0].cards[0].priceEn, 30000);
  assert.equal(result.sheets[0].showCardNames, false);
});

test("parseExcel reads UTF-8 csv files without dropping the first row", () => {
  const buffer = encodeUtf8(
    [
      "No,日本語名,英語名,セット,言語,状態,JP価格,EN価格,カテゴリ,備考,画像URL",
      "1,Black Lotus,Black Lotus,LEA,EN,SP,2400000,2600000,P9,,https://example.com/black-lotus.jpg",
      "2,意志の力,Force of Will,ALL,JP/EN,NM,24000,30000,ハイエンド,,https://example.com/fow.jpg",
    ].join("\n")
  );

  const result = parseExcel(buffer, "sample-buylist.csv");

  assert.equal(result.sheets.length, 1);
  assert.equal(result.sheets[0].cards.length, 2);
  assert.equal(result.sheets[0].cards[0].no, 1);
  assert.equal(result.sheets[0].cards[0].nameEn, "Black Lotus");
  assert.equal(result.sheets[0].cards[1].nameJp, "意志の力");
});

test("parseExcel warns when more than 36 cards are provided", () => {
  const rows: unknown[][] = [
    ["No", "日本語名", "英語名", "セット", "言語", "状態", "JP価格", "EN価格", "カテゴリ", "備考", "画像URL"],
  ];

  for (let index = 1; index <= 40; index++) {
    rows.push([
      index,
      `カード${index}`,
      `Card ${index}`,
      "SET",
      "EN",
      "NM",
      1000 + index,
      null,
      "Standard",
      "",
      "",
    ]);
  }

  const result = parseExcel(buildWorkbook(rows, "Standard"));

  assert.equal(result.sheets[0].cards.length, 36);
  assert.equal(result.warnings.length, 1);
  assert.match(result.warnings[0].message, /36/);
});

test("parseExcel falls back to fixed-column parsing for legacy format", () => {
  const buffer = buildWorkbook(
    [
      ["legacy format"],
      ["generated by old export"],
      [1, "湿地の干潟", "Marsh Flats", "ZEN", "JP", "SP", "2200", "", "フェッチランド", "", "https://example.com/marsh-flats.jpg"],
    ],
    "モダン・レガシー"
  );

  const result = parseExcel(buffer);
  const card = result.sheets[0].cards[0];

  assert.equal(card.nameEn, "Marsh Flats");
  assert.equal(card.set, "ZEN");
  assert.equal(card.isLand, true);
});
